name: Bug report
description: Report a bug with the godot-cpp template
body:

- type: markdown
  attributes:
    value: |
      - Write a descriptive issue title above.
- type: input
  attributes:
    label: Godot version
    description: >
      Specify the Git commit hash of your Godot build.
    placeholder: v4.0.stable.official [92bee43ad]
  validations:
    required: true

- type: input
  attributes:
    label: System information
    description: |
      Specify the OS version. You can easily copy this from the Godot editor file menu bar via Help -> Copy System Info.
    placeholder: Windows 11 (build 26200) - Multi-window, 2 monitors - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3080 (NVIDIA; 32.0.15.9144) - AMD Ryzen 9 9950X 16-Core Processor (32 threads) - 61.63 GiB memory
  validations:
    required: true

- type: textarea
  attributes:
    label: Issue description
    description: |
      Describe your issue briefly. What doesn't work, and how do you expect it to work instead?
      You can include images or videos with drag and drop, and format code blocks or logs with <code>```</code> tags.
  validations:
    required: true