name: Slang Build
description: Build Slang

inputs:
  platform:
    required: true
    default: 'windows'
    description: Platform to build on
  cmake-preset:
    required: true
    default: 'vs2022'
    description: CMake preset
  build-preset:
    default: 'releaseWithDebugInfo'
    description: CMake preset
  slang-location:
    default: 'slang'
    description: Slang source code location.
  lib-type:
    default: 'SHARED'
    description: How to build the slang library

runs:
  using: composite
  steps:
    - name: Cache Slang build
      id: cache-slang
      uses: actions/cache@v4
      with:
        path: ${{ inputs.slang-location }}/build
        key: slang-build-${{ runner.os }}-${{ inputs.build-preset }}-${{ hashFiles(format('{0}/CMakeLists.txt', inputs.slang-location), format('{0}/**/CMakeLists.txt', inputs.slang-location)) }}
        restore-keys: |
          slang-build-${{ runner.os }}-${{ inputs.build-preset }}-
    - name: Configure Windows CMake
      if: ${{ inputs.platform == 'windows' && steps.cache-slang.outputs.cache-hit != 'true' }}
      shell: pwsh
      run: cmake --preset ${{ inputs.cmake-preset }} -DSLANG_LIB_TYPE=${{ inputs.lib-type }}
      working-directory: ${{ inputs.slang-location }}
    - name: Build Windows CMake
      if: ${{ inputs.platform == 'windows' && steps.cache-slang.outputs.cache-hit != 'true' }}
      shell: pwsh
      run: cmake --build --preset ${{ inputs.build-preset }}
      working-directory: ${{ inputs.slang-location }}
